# Generated by Django 4.1.3 on 2022-12-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(max_length=124)),
                ('order_date', models.DateTimeField()),
                ('order_items', models.JSONField()),
                ('order_tax_amount', models.IntegerField(max_length=40)),
                ('order_amount', models.IntegerField(max_length=40)),
                ('order_offer_applied', models.BooleanField(default=0)),
                ('order_offer_name', models.CharField(max_length=40)),
                ('order_discount_amount', models.IntegerField(max_length=10)),
                ('order_billed_amount', models.IntegerField(max_length=40)),
                ('order_submitter_name', models.CharField(max_length=255)),
                ('order_payment_method', models.CharField(max_length=124)),
                ('order_medium', models.CharField(max_length=40)),
            ],
        ),
    ]
