# Generated by Django 4.1.3 on 2023-01-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_food_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
