# Generated by Django 4.1.3 on 2022-12-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_billed_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_discount_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_tax_amount',
            field=models.IntegerField(),
        ),
    ]
