# Generated by Django 4.1.3 on 2023-01-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_food_catagory_food_food_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_category',
            new_name='food_catagory',
        ),
    ]
